import { createContext } from 'react';
import { IState, IAppContext } from './interfaces';

export const DefaultState: IState = {
  cards: [
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "mens",
      type: "article",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "training",
      type: "gallery",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "womens",
      type: "video",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "academy",
      type: "video",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "academy",
      type: "article",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "mens",
      type: "article",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "womens",
      type: "article",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "mens",
      type: "article",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "womens",
      type: "gallery",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "womens",
      type: "gallery",
      categoryUrl: "https://www.quins.co.uk/",
    },
    {
      title: "Epicurus in armatum hostem impetum fecisse",
      url: "https://www.google.co.uk",
      date: "24 Nov 2021",
      featuredImage: "https://picsum.photos/500",
      category: "training",
      type: "video",
      categoryUrl: "https://www.quins.co.uk/",
    },
  ],
}

export const AppContext = createContext<IAppContext>({
  state: DefaultState,
});